//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblCart
{
    public int Id { get; set; }
    public string ClientID { get; set; }
    public int ProductID { get; set; }
    public int Amount { get; set; }
    public Nullable<System.DateTime> DatePurchased { get; set; }
    public bool IsInCart { get; set; }

    public virtual tblProduct tblProduct { get; set; }
}

public partial class tblProduct
{
    public tblProduct()
    {
        this.tblCarts = new HashSet<tblCart>();
    }

    public int Id { get; set; }
    public int TypeId { get; set; }
    public string Name { get; set; }
    public int Price { get; set; }
    public string Description { get; set; }
    public string Image { get; set; }

    public virtual ICollection<tblCart> tblCarts { get; set; }
    public virtual tblProductType tblProductType { get; set; }
}

public partial class tblProductType
{
    public tblProductType()
    {
        this.tblProducts = new HashSet<tblProduct>();
    }

    public int Id { get; set; }
    public string Name { get; set; }

    public virtual ICollection<tblProduct> tblProducts { get; set; }
}
